name: 'Setup Java and Maven'
description: 'Setup Java and Maven for pipeline'
inputs:
  github-token:
    description: 'Token used to reach maven.pkg.github.com'
    required: true
  java-version:
    description: 'Java SDK version to use'
    required: false
    default: '21'
runs:
  using: "composite"
  steps:
    - name: Create maven .m2 settings
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: '[{"id": "github", "name": "github", "url": "https://maven.pkg.github.com/navikt/familie-felles", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" }}]'
        servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ inputs.github-token }}" }]'
        output_file: 'maven-settings.xml'
    - name: Set up JDK-${{ inputs.java-version }} with cache
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: '3.9.5'
