name: 'Build and push docker image'
description: 'Build and push docker image'
inputs:
  push-image:
    required: false
    description: 'Push the docker image (true|false)'
    default: 'false'
  byosbom: # https://doc.nais.io/services/vulnerabilities/reference/#known-limitations-and-alternatives
    required: false
    description: 'Bring your own SBOM, required for analyzing nested dependencies in maven'
    default: 'auto-generate-for-me-please.json' # This is the default value in nais/docker-build-push.
  image-suffix:
    required: false
    description: 'Appends given value to the image name'
    default: ''
outputs:
  image:
    description: 'Image name'
    value: ${{ steps.docker-build-push.outputs.image }}
runs:
  using: 'composite'
  steps:
    - name: Build and push docker image
      id: docker-build-push
      uses: nais/docker-build-push@87f920b0411b987d9a1fd4113aa384e1e3b54f2c # ratchet:nais/docker-build-push@v0
      with:
        pull: true
        team: 'teamfamilie'
        push_image: ${{ inputs.push-image }}
        byosbom: ${{ inputs.byosbom }}
        image_suffix: ${{ inputs.image-suffix }}
