name: 'Build maven'
description: 'Build maven with specified command'
inputs:
  maven-command:
    description: 'What maven command to run'
    required: false
    default: 'install'
  skip-tests:
    description: 'Skip tests'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Maven ${{ inputs.maven-command }}
      shell: bash
      run: |
        mvn ${{ inputs.maven-command }} \
          --settings maven-settings.xml \
          --errors \
          --batch-mode \
          --no-transfer-progress \
          ${{ (inputs.skip-tests == 'true' && '-DskipTests') || '-Dsurefire.rerunFailingTestsCount=2' }}
