name: 'Maven install'
description: 'Maven install'
inputs:
  skip-tests:
    description: 'Skip tests'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Maven install
      shell: bash
      run: |
        mvn install \
          --settings maven-settings.xml \
          --errors \
          --batch-mode \
          --no-transfer-progress \
          ${{ (inputs.skip-tests == 'true' && '-DskipTests') || '-Dsurefire.rerunFailingTestsCount=2' }}
