name: 'Build maven'
description: 'Build maven with specified command'
inputs:
  maven-command:
    description: 'What maven command to run'
    required: false
    default: 'install'
  skip-tests:
    description: 'Skip tests'
    required: false
    default: 'false'
  profile:
    required: false
    description: 'Which maven profile to use.'
    default: ''
  with-coverage:
    required: false
    description: 'If true: sets the maven profile "coverage" (-Pcoverage)'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Maven ${{ inputs.maven-command }}
      shell: bash
      env:
        MAVEN_OPTS: -Xss1024M -Xmx2048M
      run: |
        mvn ${{ inputs.maven-command }} \
          --settings maven-settings.xml \
          --errors \
          --batch-mode \
          --no-transfer-progress \
          --quiet \
          ${{ (inputs.skip-tests == 'true' && '-DskipTests') || '-Dsurefire.rerunFailingTestsCount=2' }}
          ${{ inputs.profile && format('-P{0}', inputs.profile) || '' }} \
          ${{ inputs.with-coverage == 'true' && '-Pcoverage' || '' }} \
