name: 'Maven install'
description: 'Maven install'
inputs:
  skip-tests:
    description: 'Skip tests'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Maven install
      shell: bash
      run: |
        mvn install -s maven-settings.xml -e -B ${{ (inputs.skip-tests == 'true' && '-DskipTests') || '-Dsurefire.rerunFailingTestsCount=2' }}
