name: 'Trivy'
description: 'Run Trivy vulnerability scanner and upload results'
inputs:
  image:
    required: true
    description: 'Image to analyze (full path) example: europe-north1-docker.pkg.dev/nais-management-233d/teamfamilie/familie-ks-sak:2025.02.20-18.48-c123d9b'
runs:
  using: 'composite'
  steps:
    - uses: nais/login@e7cf2c159677dc7c7d599feff5f808f2bf59c7cf # ratchet:nais/login@v0
      with:
        team: 'teamfamilie'
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # ratchet:aquasecurity/trivy-action@v0.30
      env: # Workaround until fixed: https://github.com/aquasecurity/trivy-action/issues/389
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db
        TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db,aquasec/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db
      with:
        image-ref: ${{ inputs.image }}
        format: 'sarif'
        output: 'trivy.sarif'
        severity: 'HIGH,CRITICAL'
        limit-severities-for-sarif: true
    - name: Upload results to GitHub Security
      uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841 # ratchet:github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy.sarif'
