name: 'Trivy'
description: 'Run Trivy vulnerability scanner and upload results'
inputs:
  image:
    required: true
    description: 'Image to analyze (full path) example: europe-north1-docker.pkg.dev/nais-management-233d/teamfamilie/familie-ks-sak:2025.02.20-18.48-c123d9b'
runs:
  using: 'composite'
  steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # ratchet:aquasecurity/trivy-action@0.35.0
      env: # Workaround until fixed: https://github.com/aquasecurity/trivy-action/issues/389
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db
        TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db,aquasec/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db
      with:
        image-ref: ${{ inputs.image }}
        format: 'sarif'
        output: 'trivy.sarif'
        severity: 'HIGH,CRITICAL'
        limit-severities-for-sarif: true
        version: 'latest'
    - name: Upload results to GitHub Security
      uses: github/codeql-action/upload-sarif@b1bff81932f5cdfc8695c7752dcee935dcd061c8 # ratchet:github/codeql-action/upload-sarif@v4
      with:
        sarif_file: 'trivy.sarif'
