name: Build maven app
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: 'Which runner image to run the workflow.'
        default: 'ubuntu-latest'
      java-version:
        required: false
        type: string
        description: 'Which Java SDK version to build app.'
        default: '21'
      build-image:
        required: false
        type: boolean
        description: 'Build docker image?'
        default: true
      push-image:
        required: false
        type: boolean
        description: 'Push docker image?'
        default: false
    outputs:
      image:
        description: "Image name"
        value: ${{ jobs.build-maven-app.outputs.image }}
jobs:
  build-maven-app:
    name: Build maven app
    permissions:
      contents: "read"
      packages: "write"
      id-token: "write"
    runs-on: ${{ inputs.runs-on }}
    env:
      TZ: "Europe/Oslo"
    outputs:
      image: ${{ steps.build-push-docker-image.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
      - name: Setup java and maven
        uses: navikt/familie-baks-gha-workflows/.github/actions/setup-java-maven@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: ${{ inputs.java-version }}
      - name: Maven install
        uses: navikt/familie-baks-gha-workflows/.github/actions/build-maven@main
        env:
          TESTCONTAINERS_REUSE_ENABLE: true
      # TODO: Sonar analyse
      - name: Bygg og push docker image
        id: build-push-docker-image
        if: inputs.build-image
        uses: navikt/familie-baks-gha-workflows/.github/actions/build-push-docker-image@main
        with:
          push-image: ${{ inputs.push-image }}
      - name: Clean up generated stuff before caching
        run: |
          rm ~/.m2/repository/no/nav/familie -r
