name: Manual deploy
on:
  workflow_call:
    inputs:
      image-name:
        required: false
        type: string
        description: 'Image name, defaults to repo name. Used for environment-specific images'
      image-tag:
        required: true
        type: string
        description: 'Image tag to deploy (example 2025.02.20-18.48-c123d9b)'
      cluster:
        required: true
        type: string
        description: 'The cluster to deploy to (dev-fss|dev-gcp|prod-fss|prod-gcp)'
      resource:
        required: true
        type: string
        description: 'The path to the nais (yaml) resource file to use'
      runs-on:
        required: false
        type: string
        description: 'Which runner image to run the workflow.'
        default: 'ubuntu-latest'

env:
  IMAGE_REGISTRY: europe-north1-docker.pkg.dev/nais-management-233d/teamfamilie
  IMAGE_NAME: ${{ inputs.image-name || github.event.repository.name }}
  IMAGE_TAG: ${{ inputs.image-tag }}

jobs:
  manual-deploy:
    name: Manual deploy
    permissions:
      contents: read
      id-token: write # nais/deploy
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # ratchet:step-security/harden-runner@v2.21.0
        with:
          egress-policy: audit
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: Deploy to ${{ inputs.cluster }} from GAR
        uses: navikt/familie-baks-gha-workflows/.github/actions/deploy@main # ratchet:exclude
        with:
          cluster: ${{ inputs.cluster }}
          resource: ${{ inputs.resource }}
          image: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          # Imaget deployes fra en vilkårlig tag og er ikke nødvendigvis bygget fra
          # ref-en som trigget dette deployet, så vi kan ikke utlede branchen.
          # Tag-en er mer informativ enn ingenting, og er sporbar tilbake til commit.
          branch: "tag:${{ inputs.image-tag }}"
