name: Digestabot updates

on:
  workflow_call:
    inputs:
      digestabot-client-id:
        required: true
        type: string
    secrets:
      DIGESTABOT_PRIVATE_KEY:
        required: true

jobs:
  digestabot-updates:
    name: Digestabot updates
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # ratchet:step-security/harden-runner@v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Create GitHub app token for Digestabot
        id: digestabot-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # ratchet:actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ inputs.digestabot-client-id }}
          private-key: ${{ secrets.DIGESTABOT_PRIVATE_KEY }}
      - uses: navikt/digestabot@3302a753e533ceb9ec216de7f78345436cd636e3 # ratchet:navikt/digestabot@v1.2
        with:
          token: ${{ steps.digestabot-token.outputs.token }}
          team: teamfamilie
          branch-for-pr: 'digestabot-update-digests'
          commit-message: 'Bump Docker image (digestabot)'
          title-for-pr: 'Bump Docker image (digestabot)'
          description-for-pr: 'Bumper Chainguard Docker image til nyeste tilgjengelige versjon.'
