name: Digestabot updates

on:
  workflow_call:
    inputs:
      digestabot-client-id:
        required: true
        type: string
    secrets:
      DIGESTABOT_PRIVATE_KEY:
        required: true

jobs:
  digestabot-updates:
    name: Digestabot updates
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # ratchet:step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          persist-credentials: false
      - name: Create GitHub app token for Digestabot
        id: digestabot-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # ratchet:actions/create-github-app-token@v3.1.1
        with:
          client-id: ${{ inputs.digestabot-client-id }}
          private-key: ${{ secrets.DIGESTABOT_PRIVATE_KEY }}
      - uses: navikt/digestabot@e4b413f1eed3c97f7fd4ffa1d05204de9944d0a9 # ratchet:navikt/digestabot@v1.1.1
        with:
          token: ${{ steps.digestabot-token.outputs.token }}
          team: teamfamilie
          branch-for-pr: 'digestabot-update-digests'
          commit-message: 'Bump Docker image (digestabot)'
          title-for-pr: 'Bump Docker image (digestabot)'
          description-for-pr: 'Bumper Chainguard Docker image til nyeste tilgjengelige versjon.'
