name: Notify failed workflow
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: 'Which runner image to run the workflow.'
        default: 'ubuntu-latest'
    secrets:
      BAKS_DEPLOYMENTS_SLACK_WEBHOOK:
        required: true

jobs:
  notify-failed-workflow:
    name: Notify failed workflow
    runs-on: ${{ inputs.runs-on }}
    permissions: {}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # ratchet:step-security/harden-runner@v2.21.0
        with:
          egress-policy: audit
      - name: Post in slack
        uses: navikt/familie-baks-gha-workflows/.github/actions/notify-slack@main # ratchet:exclude
        with:
          message: "Workflow: `${{ github.workflow }}` feilet for ${{ github.repository }} - ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          slack_webhook: ${{ secrets.BAKS_DEPLOYMENTS_SLACK_WEBHOOK }}
