name: Notify slack
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: 'Which runner image to run the workflow.'
        default: 'ubuntu-latest'
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify-slack:
    name: Notify slack
    runs-on: ${{ inputs.runs-on }}
    permissions: {}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # ratchet:step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Post error in slack
        run: |
          curl -X POST --data "{\"text\": \"Workflow: $GITHUB_WORKFLOW feilet for $GITHUB_REPOSITORY - $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\"}" $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
