name: Pull request maven
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: 'Which runner image to run the workflow.'
        default: 'ubuntu-latest'
      java-version:
        required: true
        type: string
        description: 'Which Java SDK version to build app.'
      with-coverage:
        required: false
        type: boolean
        description: 'If true: sets the maven profile "coverage" and uploads the coverage report'
        default: false
      profile:
        required: false
        type: string
        description: 'Which maven profile to use for tests.'
        default: ''
      coverage-artifact-name:
        required: false
        type: string
        default: ${{ inputs.with-coverage && inputs.profile || ''}}
      coverage-artifact-path:
        required: false
        type: string
        default: ${{ inputs.with-coverage && format('coverage/{0}', inputs.profile) || '' }}
jobs:
  pull-request-maven:
    name: Pull request maven
    if: github.actor != 'team-baks-digestabot[bot]'
    permissions:
      contents: read # fetch repo
    runs-on: ${{ inputs.runs-on }}
    env:
      TZ: 'Europe/Oslo'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # ratchet:step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Setup java and maven
        uses: navikt/familie-baks-gha-workflows/.github/actions/setup-java-maven@main # ratchet:exclude
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: ${{ inputs.java-version }}
      - name: Maven verify
        uses: navikt/familie-baks-gha-workflows/.github/actions/build-maven@main # ratchet:exclude
        env:
          TESTCONTAINERS_REUSE_ENABLE: true
        with:
          maven-command: 'verify'
          skip-tests: false
          profile: ${{ inputs.profile }}
          with-coverage: ${{ inputs.with-coverage }}
      - name: Upload code coverage report
        if: ${{ inputs.with-coverage }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # ratchet:actions/upload-artifact@v7.0.1
        with:
          name: ${{ inputs.coverage-artifact-name }}
          path: ${{ inputs.coverage-artifact-path }}
          retention-days: 1
          overwrite: true
