name: Scan vulnerabilities pnpm
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        description: 'Which runner image to run the workflow.'
        default: 'ubuntu-latest'
      node-version:
        required: true
        type: string
        description: 'Which Node version to build app.'
      pnpm-version:
        required: false
        type: string
        description: 'Which pnpm version to use.'
        default: '10'
    secrets:
      READER_TOKEN:
        required: false
jobs:
  scan-vulnerabilities:
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: write # to write sarif
      security-events: write # push sarif to github security
      id-token: write # nais/login
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # ratchet:step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Nais login
        uses: nais/login@c88ada9ce583928e1c84d2fd5c45cfacdd18d5de # ratchet:nais/login@v0
        with:
          team: teamfamilie
      # CodeQL scan
      - name: Initialize CodeQL
        uses: github/codeql-action/init@c10b8064de6f491fea524254123dbe5e09572f13 # ratchet:github/codeql-action/init@v4
        with:
          languages: javascript-typescript, actions
          config: |
            paths-ignore:
              - node_modules/
              - dist/
              - dist_frontend/
              - dist_backend/
              - frontend_production/
      - name: Set up node and install pnpm packages
        uses: navikt/familie-baks-gha-workflows/.github/actions/setup-node-pnpm@main # ratchet:exclude
        with:
          node-version: ${{ inputs.node-version }}
          pnpm-version: ${{ inputs.pnpm-version }}
          reader-token: ${{ secrets.READER_TOKEN }}
      - name: pnpm build
        run: pnpm build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@c10b8064de6f491fea524254123dbe5e09572f13 # ratchet:github/codeql-action/analyze@v4
      # Trivy scan
      - name: Build docker image
        id: build-docker-image
        uses: navikt/familie-baks-gha-workflows/.github/actions/build-docker-image@main # ratchet:exclude
      - name: Run Trivy vulnerability scanner and upload results
        uses: navikt/familie-baks-gha-workflows/.github/actions/trivy@main # ratchet:exclude
        with:
          image: ${{ steps.build-docker-image.outputs.image-ref }}
